version = "0.6.0"
author = "Nim Nitro developers"
license = "MIT"
description = "Nitro state channels"

requires "nimcrypto >= 0.6.0"
requires "questionable >= 0.10.10"
requires "contractabi >= 0.7.1"
requires "secp256k1 >= 0.6.0"
requires "stint >= 0.8.0"
requires "stew >= 0.2.0"
